(() => {
  const data = window.GAME_DATA;
  const mode = window.GAME_MODE;
  if (!data || !mode) throw new Error('Game data or game mode is missing.');
  document.documentElement.style.setProperty('--accent', data.accent);
  document.documentElement.style.setProperty('--accent-dark', data.dark);

  const names = {spin:'Spin the Wheel',jeopardy:'Jeopardy',match:'Memory Match',millionaire:'Millionaire',snake:'Snake',hangman:'Hangman'};
  const icons = {spin:'🎡',jeopardy:'🧠',match:'🃏',millionaire:'💰',snake:'🐍',hangman:'🪢'};
  document.title = `${data.topic} ${names[mode]} | May Learning Hub`;
  document.body.innerHTML = `
    <nav><a href="../../../../index.html" class="logo">May Learning Hub</a><div class="nav-links"><a href="../../../../Collab-Hub.html">Collaboration Hub</a><a href="${data.presentation}">Presentation</a><a href="games.html" class="active">Games Menu</a></div></nav>
    <header class="page-header"><div class="grade-badge">Grade 12 ${data.topic}</div><h1 class="page-title">${icons[mode]} ${names[mode]}</h1><p class="page-subtitle">A playable ${data.topic} revision challenge with instant feedback.</p><div class="header-actions"><a class="header-btn" href="${data.presentation}">📝 Presentation</a><a class="header-btn secondary" href="games.html">← All Game Types</a></div></header>
    <main class="game-container"><section class="game-shell" id="gameRoot"></section></main>
    <footer>&copy; 2026 May Learning Hub &middot; Grade 12 Mathematics ${data.topic}</footer>`;
  const root = document.getElementById('gameRoot');
  const shuffle = list => { const copy=[...list]; for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];} return copy; };

  function initSpin(){
    root.innerHTML = `<div class="game-heading"><h2>Spin for a Challenge</h2><div class="status-pills"><span class="pill" id="spinCount">Questions: 0</span></div></div><div class="wheel-wrap"><div class="wheel-stage"><div class="wheel-pointer"></div><div class="wheel" id="wheel"></div></div><div class="panel wheel-question"><p class="prompt" id="spinPrompt">Press the button and let the wheel choose a question.</p><div class="answer-box" id="spinAnswer" hidden></div><div class="button-row"><button class="primary-btn" id="spinBtn">Spin the Wheel</button><button class="secondary-btn" id="revealBtn" hidden>Reveal Answer</button></div></div></div>`;
    const wheel=document.getElementById('wheel'), prompt=document.getElementById('spinPrompt'), answer=document.getElementById('spinAnswer'), spinBtn=document.getElementById('spinBtn'), reveal=document.getElementById('revealBtn');
    let rotation=0,current=null,count=0;
    spinBtn.addEventListener('click',()=>{spinBtn.disabled=true;answer.hidden=true;reveal.hidden=true;prompt.textContent='The wheel is choosing…';const index=Math.floor(Math.random()*data.spin.length);rotation+=1440+(index*45)+Math.floor(Math.random()*30);wheel.style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{current=data.spin[index];prompt.textContent=current.question;reveal.hidden=false;spinBtn.disabled=false;spinBtn.textContent='Spin Again';count++;document.getElementById('spinCount').textContent=`Questions: ${count}`;},1150);});
    reveal.addEventListener('click',()=>{answer.textContent=current.answer;answer.hidden=false;reveal.hidden=true;});
  }

  function initJeopardy(){
    root.innerHTML=`<div class="game-heading"><h2>${data.topic} Jeopardy Board</h2><div class="status-pills"><span class="pill" id="jeopardyScore">Score: 0</span><span class="pill" id="cluesLeft">Clues: 16</span></div></div><div class="jeopardy-board" id="board"></div><div class="panel clue-panel" id="cluePanel"><p class="prompt">Choose a value from the board.</p></div>`;
    const board=document.getElementById('board'),panel=document.getElementById('cluePanel');let score=0,left=16,active=null;
    data.jeopardy.forEach(cat=>board.insertAdjacentHTML('beforeend',`<div class="category">${cat.name}</div>`));
    for(let q=0;q<4;q++) data.jeopardy.forEach((cat,c)=>board.insertAdjacentHTML('beforeend',`<button class="clue-btn" data-cell="${c}-${q}">R${cat.questions[q].value}</button>`));
    board.addEventListener('click',event=>{const btn=event.target.closest('.clue-btn');if(!btn||btn.disabled)return;const [c,q]=btn.dataset.cell.split('-').map(Number);active={btn,item:data.jeopardy[c].questions[q]};btn.disabled=true;left--;document.getElementById('cluesLeft').textContent=`Clues: ${left}`;panel.innerHTML=`<p class="prompt">${active.item.question}</p><button class="primary-btn" id="showClueAnswer">Show Answer</button>`;document.getElementById('showClueAnswer').addEventListener('click',()=>{panel.innerHTML=`<p class="prompt">${active.item.question}</p><div class="answer-box">${active.item.answer}</div><div class="score-controls"><button class="primary-btn" data-result="correct">I got it right</button><button class="danger-btn" data-result="wrong">I got it wrong</button></div>`;});});
    panel.addEventListener('click',event=>{const result=event.target.dataset.result;if(!result||!active)return;score+=result==='correct'?active.item.value:-active.item.value;document.getElementById('jeopardyScore').textContent=`Score: ${score}`;panel.innerHTML=left?'<p class="prompt">Choose another value from the board.</p>':`<p class="prompt">Board complete! Final score: ${score}</p><button class="primary-btn" onclick="location.reload()">Play Again</button>`;active=null;});
  }

  function initMatch(){
    root.innerHTML=`<div class="game-heading"><h2>Match Terms and Meanings</h2><div class="status-pills"><span class="pill" id="moves">Moves: 0</span><span class="pill" id="pairs">Pairs: 0/${data.match.length}</span></div></div><div class="match-grid" id="matchGrid"></div><div class="feedback" id="matchFeedback">Turn over two cards to find a matching pair.</div><div class="button-row"><button class="secondary-btn" id="restartMatch">Shuffle Again</button></div>`;
    const grid=document.getElementById('matchGrid'),feedback=document.getElementById('matchFeedback');let first=null,locked=false,moves=0,matched=0;
    const cards=shuffle(data.match.flatMap((pair,id)=>[{id,text:pair.term,type:'term'},{id,text:pair.definition,type:'definition'}]));
    cards.forEach((card,index)=>grid.insertAdjacentHTML('beforeend',`<button class="match-card" data-index="${index}" data-pair="${card.id}">?</button>`));
    grid.addEventListener('click',event=>{const btn=event.target.closest('.match-card');if(!btn||locked||btn.classList.contains('revealed')||btn.classList.contains('matched'))return;const card=cards[Number(btn.dataset.index)];btn.textContent=card.text;btn.classList.add('revealed');if(!first){first={btn,card};return;}moves++;document.getElementById('moves').textContent=`Moves: ${moves}`;if(first.card.id===card.id&&first.card.type!==card.type){first.btn.classList.replace('revealed','matched');btn.classList.replace('revealed','matched');matched++;document.getElementById('pairs').textContent=`Pairs: ${matched}/${data.match.length}`;feedback.textContent='Match found!';first=null;if(matched===data.match.length)feedback.innerHTML='<strong>Excellent!</strong> You matched every pair.';}else{locked=true;feedback.textContent='Not a match. Try again.';const previous=first;setTimeout(()=>{previous.btn.textContent='?';previous.btn.classList.remove('revealed');btn.textContent='?';btn.classList.remove('revealed');first=null;locked=false;},750);}});
    document.getElementById('restartMatch').addEventListener('click',()=>location.reload());
  }

  function initMillionaire(){
    const money=['R100','R200','R300','R500','R1 000','R2 000','R4 000','R8 000','R16 000','R32 000'];
    root.innerHTML=`<div class="game-heading"><h2>Who Wants to Be a ${data.topic} Millionaire?</h2><div class="status-pills"><span class="pill" id="moneyLevel">Prize: R0</span></div></div><div class="money-layout"><div><button class="secondary-btn lifeline" id="fiftyBtn">Use 50:50</button><div class="panel"><p class="prompt" id="moneyQuestion"></p><div class="options" id="moneyOptions"></div><div class="feedback" id="moneyFeedback">Choose carefully—one wrong answer ends the run.</div><div class="button-row"><button class="primary-btn" id="moneyNext" hidden>Next Question</button><button class="secondary-btn" id="moneyRestart" hidden>Play Again</button></div></div></div><ol class="money-ladder" id="moneyLadder"></ol></div>`;
    const ladder=document.getElementById('moneyLadder'),question=document.getElementById('moneyQuestion'),options=document.getElementById('moneyOptions'),feedback=document.getElementById('moneyFeedback'),next=document.getElementById('moneyNext'),restart=document.getElementById('moneyRestart'),fifty=document.getElementById('fiftyBtn');let index=0,finished=false;
    money.forEach((amount,i)=>ladder.insertAdjacentHTML('beforeend',`<li data-level="${i}">${amount}</li>`));
    function render(){finished=false;next.hidden=true;restart.hidden=true;feedback.textContent='Choose carefully—one wrong answer ends the run.';question.textContent=data.millionaire[index].question;options.replaceChildren();data.millionaire[index].options.forEach((text,i)=>{const btn=document.createElement('button');btn.className='option-btn';btn.dataset.option=i;btn.textContent=`${String.fromCharCode(65+i)}. ${text}`;options.appendChild(btn);});document.querySelectorAll('.money-ladder li').forEach(li=>li.classList.toggle('active',Number(li.dataset.level)===index));}
    options.addEventListener('click',event=>{const btn=event.target.closest('.option-btn');if(!btn||finished)return;finished=true;const item=data.millionaire[index],chosen=Number(btn.dataset.option);[...options.children].forEach((b,i)=>{b.disabled=true;if(i===item.answer)b.classList.add('correct');});if(chosen===item.answer){document.getElementById('moneyLevel').textContent=`Prize: ${money[index]}`;feedback.className='feedback good';feedback.textContent=`Correct! ${item.explanation}`;if(index===data.millionaire.length-1){feedback.textContent=`You won ${money[index]}! ${item.explanation}`;restart.hidden=false;}else next.hidden=false;}else{btn.classList.add('wrong');feedback.className='feedback bad';feedback.textContent=`Game over. ${item.explanation}`;restart.hidden=false;}});
    next.addEventListener('click',()=>{index++;feedback.className='feedback';render();});restart.addEventListener('click',()=>location.reload());fifty.addEventListener('click',()=>{const item=data.millionaire[index];const wrong=[0,1,2,3].filter(i=>i!==item.answer);shuffle(wrong).slice(0,2).forEach(i=>options.children[i].hidden=true);fifty.disabled=true;});render();
  }

  function initSnake(){
    root.innerHTML=`<div class="game-heading"><h2>Eat the Correct Answer</h2><div class="status-pills"><span class="pill" id="snakeScore">Score: 0</span><span class="pill" id="snakeLives">Lives: 3</span></div></div><div class="snake-layout"><div><div class="snake-board" id="snakeBoard"></div><div class="snake-controls"><button class="up" data-dir="up">▲</button><button class="left" data-dir="left">◀</button><button class="down" data-dir="down">▼</button><button class="right" data-dir="right">▶</button></div></div><div class="panel"><p class="prompt" id="snakeQuestion"></p><div id="snakeLegend"></div><div class="feedback" id="snakeFeedback">Press Start, then use the arrow keys or controls.</div><div class="button-row"><button class="primary-btn" id="snakeStart">Start Game</button><button class="secondary-btn" id="snakeRestart" hidden>Restart</button></div></div></div>`;
    const board=document.getElementById('snakeBoard'),question=document.getElementById('snakeQuestion'),legend=document.getElementById('snakeLegend'),feedback=document.getElementById('snakeFeedback'),start=document.getElementById('snakeStart'),restart=document.getElementById('snakeRestart');let snake,dir,pending,foods=[],qIndex=0,score=0,lives=3,timer=null,running=false;
    function randomSpot(blocked){let p;do{p={x:Math.floor(Math.random()*10),y:Math.floor(Math.random()*10)}}while(blocked.some(b=>b.x===p.x&&b.y===p.y));return p;}
    function setQuestion(){const item=data.snake[qIndex];question.textContent=item.question;legend.innerHTML=item.options.map((o,i)=>`<span class="option-key"><strong>${String.fromCharCode(65+i)}</strong> — ${o}</span>`).join('');foods=[];const blocked=[...snake];for(let i=0;i<4;i++){const p=randomSpot([...blocked,...foods]);foods.push({...p,index:i});}renderBoard();}
    function renderBoard(){board.replaceChildren();for(let y=0;y<10;y++)for(let x=0;x<10;x++){const cell=document.createElement('div');cell.className='snake-cell';const bodyIndex=snake.findIndex(s=>s.x===x&&s.y===y);const food=foods.find(f=>f.x===x&&f.y===y);if(bodyIndex===0)cell.classList.add('head');else if(bodyIndex>0)cell.classList.add('body');if(food){cell.classList.add('food');cell.textContent=String.fromCharCode(65+food.index);}board.appendChild(cell);}}
    function reset(){clearInterval(timer);snake=[{x:4,y:5},{x:3,y:5},{x:2,y:5}];dir={x:1,y:0};pending=dir;qIndex=0;score=0;lives=3;running=false;start.hidden=false;restart.hidden=true;document.getElementById('snakeScore').textContent='Score: 0';document.getElementById('snakeLives').textContent='Lives: 3';feedback.textContent='Press Start, then use the arrow keys or controls.';setQuestion();}
    function change(name){const map={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}},next=map[name];if(next.x!==-dir.x||next.y!==-dir.y)pending=next;}
    function gameOver(message){clearInterval(timer);running=false;feedback.className='feedback bad';feedback.textContent=message;restart.hidden=false;}
    function tick(){dir=pending;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>9||head.y<0||head.y>9||snake.some(s=>s.x===head.x&&s.y===head.y)){gameOver(`Game over! Final score: ${score}.`);return;}snake.unshift(head);const food=foods.find(f=>f.x===head.x&&f.y===head.y);if(food){const item=data.snake[qIndex];if(food.index===item.answer){score++;feedback.className='feedback good';feedback.textContent=`Correct! ${item.explanation}`;document.getElementById('snakeScore').textContent=`Score: ${score}`;qIndex=(qIndex+1)%data.snake.length;setQuestion();}else{snake.pop();lives--;feedback.className='feedback bad';feedback.textContent='That was not the correct answer. Try the same question again.';document.getElementById('snakeLives').textContent=`Lives: ${lives}`;if(lives<=0){gameOver(`No lives left. Final score: ${score}.`);return;}setQuestion();}}else snake.pop();renderBoard();}
    start.addEventListener('click',()=>{if(running)return;running=true;start.hidden=true;feedback.className='feedback';feedback.textContent='Guide the snake to A, B, C, or D.';timer=setInterval(tick,420);});restart.addEventListener('click',reset);document.querySelector('.snake-controls').addEventListener('click',event=>{const name=event.target.dataset.dir;if(name)change(name);});document.addEventListener('keydown',event=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(map[event.key]){event.preventDefault();change(map[event.key]);}});reset();
  }

  function initHangman(){
    const stages=['🙂','😐','😟','😨','😵','💀','🪦'];
    root.innerHTML=`<div class="game-heading"><h2>Guess the Hidden ${data.topic} Term</h2><div class="status-pills"><span class="pill" id="hangLives">Lives: 6</span><span class="pill" id="hangScore">Solved: 0</span></div></div><div class="hangman-layout"><div class="hangman-figure" id="hangFigure">🙂</div><div class="panel"><p><strong>Clue:</strong> <span id="hangClue"></span></p><div class="word-display" id="wordDisplay"></div><div class="keyboard" id="keyboard"></div><div class="feedback" id="hangFeedback">Choose a letter.</div><div class="button-row"><button class="primary-btn" id="nextWord" hidden>Next Word</button><button class="secondary-btn" id="restartHang">Restart</button></div></div></div>`;
    const clue=document.getElementById('hangClue'),display=document.getElementById('wordDisplay'),keyboard=document.getElementById('keyboard'),feedback=document.getElementById('hangFeedback'),next=document.getElementById('nextWord'),figure=document.getElementById('hangFigure');let order=shuffle(data.hangman),index=0,guessed=new Set(),lives=6,solved=0,ended=false;
    function renderWord(){const word=order[index].word;display.innerHTML=[...word].map(ch=>`<span class="letter-slot">${guessed.has(ch)?ch:'&nbsp;'}</span>`).join('');const won=[...word].every(ch=>guessed.has(ch));if(won&&!ended){ended=true;solved++;document.getElementById('hangScore').textContent=`Solved: ${solved}`;feedback.className='feedback good';feedback.textContent='You solved it!';next.hidden=false;disableKeys();}}
    function disableKeys(){keyboard.querySelectorAll('button').forEach(b=>b.disabled=true);}
    function newWord(){guessed=new Set();lives=6;ended=false;next.hidden=true;figure.textContent=stages[0];document.getElementById('hangLives').textContent='Lives: 6';clue.textContent=order[index].clue;keyboard.replaceChildren();'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach(letter=>{const btn=document.createElement('button');btn.className='key-btn';btn.textContent=letter;btn.dataset.letter=letter;keyboard.appendChild(btn);});feedback.className='feedback';feedback.textContent='Choose a letter.';renderWord();}
    keyboard.addEventListener('click',event=>{const btn=event.target.closest('.key-btn');if(!btn||ended)return;const letter=btn.dataset.letter;btn.disabled=true;guessed.add(letter);if(order[index].word.includes(letter)){btn.classList.add('hit');feedback.className='feedback good';feedback.textContent='Good letter!';}else{btn.classList.add('miss');lives--;document.getElementById('hangLives').textContent=`Lives: ${lives}`;figure.textContent=stages[6-lives];feedback.className='feedback bad';feedback.textContent='That letter is not in the word.';if(lives===0){ended=true;display.innerHTML=[...order[index].word].map(ch=>`<span class="letter-slot">${ch}</span>`).join('');feedback.textContent=`The word was ${order[index].word}.`;next.hidden=false;disableKeys();return;}}renderWord();});
    next.addEventListener('click',()=>{index=(index+1)%order.length;newWord();});document.getElementById('restartHang').addEventListener('click',()=>{order=shuffle(data.hangman);index=0;solved=0;document.getElementById('hangScore').textContent='Solved: 0';newWord();});newWord();
  }

  ({spin:initSpin,jeopardy:initJeopardy,match:initMatch,millionaire:initMillionaire,snake:initSnake,hangman:initHangman}[mode])();
})();